export let produtos = [
  {
    id: 1,
    nome: "Gabinete Gamer Aigo Darkflash Durin D275M",
    preco: 250,
    categoria: "hardware",
    estoque: 13,
    imagem: "images/gabinete.png",
  },
  { id: 2, nome: "Water Cooler Atmos II LCD  Frezze", preco: 125, categoria: "hardware", estoque: 6, 
    imagem: "images/watercooler.jpg",
   },
  {
    id: 3,
    nome: "Placa Mae Gigabyte B760M Gaming X Gen5",
    preco: 980,
    categoria: "eletronico",
    estoque: 23,
    imagem: "images/placamae.png",
  },
  {
    id: 4,
    nome: "Mouse Gamer Force One Hoku Pro",
    preco: 400,
    categoria: "periferico",
    estoque: 2,
    imagem: "images/mouse.png",
  },
  {
    id: 5,
    nome: "Teclado Mecanico Havit KB904L",
    preco: 230,
    categoria: "periferico",
    estoque: 8,
    imagem: "images/teclado.jpg",
  },
  {
    id: 6,
    nome: "Headset Havit 17kcat PRO suround",
    preco: 157,
    categoria: "periferico",
    estoque: 10,
    imagem: "images/headset.jpg",
  },
  {
    id: 7,
    nome: "Cadeira MX-12",
    preco: 438,
    categoria: "periferico",
    estoque: 5,
    imagem: "images/cadeira.jpg",
  },
  {
    id: 8,
    nome: "Microfone 03 Pdc",
    preco: 200,
    categoria: "periferico",
    estoque: 16,
    imagem: "images/microfone.jpg",
  },
  {
    id: 9,
    nome: "Processador Ryzen 7 5700X",
    preco: 998,
    categoria: "hardware",
    estoque: 3,
    imagem: "images/processador.png",
  },
  {
    id: 10,
    nome: "Monitor 240hz OLed QHD",
    preco: 2100,
    categoria: "eletronico",
    estoque: 7,
    imagem: "images/monitor.png",
  },
];